;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Mon Oct 14 2024
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================

DATA	SEGMENT
   PORTA EQU 0b0H	; 0101 0000 0001
   PORTB EQU 0b2H	; 0101 0000 0000
   PORTC equ 0b4h	; 0101 0000 000X
			; 1098 7654 3210
DATA	ENDS

STK	SEGMENT STACK
   DW 200 DUP(?)
STK	ENDS

CODE SEGMENT PUBLIC 'CODE'
      ASSUME CS:CODE, DS:DATA
      
      ORG 0000H
      
      XOR AX, AX
      XOR BX, BX
      XOR CX, CX
      XOR DX, DX
      
START:
   WAIT_INPUT:
      MOV DX, PORTB
      IN AL, DX
      
      cmp al, 00h
      je pawng
      CMP AL, 01H
      JE ONTANAN
      CMP AL, 02H
      JE TUYOK
      CMP AL, 04H
      JE AHAS
      cmp al, 08h
      je RUSSIAN
      CMP AL, 10000B
      JE TOINK
      CMP AL, 100000B
      JE TESTING
      JMP WAIT_INPUT
TESTING:
	 MOV DX, PORTA
	 MOV AX, 0FF00H
	 OUT DX, AX
	 JMP WAIT_INPUT
      
RUSSIAN:
   ;1 2 3 4 
   ;5 6 7 8
   MOV DX, PORTA
   
   MOV AL, 00000001B
   OUT DX, AL
   MOV AL, 00100000B
   OUT DX, AL
   MOV AL, 00000100B
   OUT DX, AL
   MOV AL, 10000000B
   OUT DX, AL
   MOV AL, 00001000B
   OUT DX, AL
   MOV AL, 01000000B
   OUT DX, AL
   MOV AL, 00000010B
   OUT DX, AL
   MOV AL, 00010000B
   OUT DX, AL
   JMP WAIT_INPUT

TOINK:
   MOV DX, PORTA
   ;1 2 3 4
   ;5 6 7 8
   MOV AL, 00110000B
   OUT DX, AL
   MOV AL, 00010010B
   OUT DX, AL
   MOV AL, 01100000B
   OUT DX, AL
   MOV AL, 01000100B
   OUT DX, AL
   MOV AL, 11000000B
   OUT DX, AL
   MOV AL, 10001000B
   OUT DX, AL
   MOV AL, 11000000B
   OUT DX, AL
   MOV AL, 01000100B
   OUT DX, AL
   MOV AL, 01100000B
   OUT DX, AL
   MOV AL, 00100010B
   OUT DX, AL
   MOV AL, 00110000B
   OUT DX,AL
   MOV AL, 00010001B
   OUT DX, AL
   JMP WAIT_INPUT
      
pawng:
   mov dx, PORTA
   mov al, 00h
   out dx, al
   jmp WAIT_INPUT
ONTANAN:
   MOV DX, PORTA
   MOV AL, 11111111B
   OUT DX, AL
   JMP WAIT_INPUT
   
TUYOK:
   ;1 2 3 4
   ;5 6 7 8
   
   MOV DX, PORTA
   MOV AL, 00001001b
   OUT Dx, AL
   
   MOV AL, 00000110B
   OUT DX, AL
   
   MOV AL, 01100000B
   OUT DX, AL
   
   MOV AL, 10010000B
   OUT DX, AL
   JMP WAIT_INPUT
   
AHAS:
   ;1 2 3 4
   ;5 6 7 8
   mov dx, PORTA
   mov al, 00000011b
   out dx, al
   
   mov al, 00000110b
   out dx, al
   
   mov al, 00001100b
   out dx, al
   
   mov al, 10001000b
   out dx, al
   
   mov al, 11000000b
   out dx, al
   
   mov al, 01100000b
   out dx, al
   
   mov al, 00110000b
   out dx, al
   
   mov al, 00010001b
   out dx, al
   jmp WAIT_INPUT

   CODE ENDS
   END START
   