;==================================================
; Seven Segment Display with 8255
;==================================================

IO_SEG SEGMENT
ORG 03000H
   PORT_A   EQU 0F0H
   PORT_B   EQU 0F2H
   PORT_C   EQU 0F4H
   CNTRLREG EQU 0F6H
IO_SEG ENDS

CODE_SEG SEGMENT PUBLIC 'CODE'
        ASSUME CS:CODE_SEG

MAIN_START:

   MOV DX, CNTRLREG
   MOV AL, 89H
   OUT DX, AL

   ; Clear outputs
   MOV DX, PORT_A
   MOV AL, 00H
   OUT DX, AL

   MOV DX, PORT_B
   MOV AL, 00H
   OUT DX, AL

   CALL DELAY_1MS
   CALL DELAY_1MS

EXEC_LOOP:
   CALL CHECK_INPUT      

   CMP AL, 00000000B
   JE SHOW_0
   CMP AL, 00010000B
   JE SHOW_1
   CMP AL, 00100000B
   JE SHOW_2
   CMP AL, 00110000B
   JE SHOW_3
   CMP AL, 01000000B
   JE SHOW_4
   CMP AL, 01010000B
   JE SHOW_5
   CMP AL, 01100000B
   JE SHOW_6
   CMP AL, 01110000B
   JE SHOW_7
   CMP AL, 10000000B
   JE SHOW_8
   CMP AL, 10010000B
   JE SHOW_9

   JMP EXEC_LOOP

; Display digits
SHOW_0:
   MOV DX, PORT_B
   MOV AL, 00111111B
   OUT DX, AL
   MOV DX, PORT_A
   MOV AL, 0
   OUT DX, AL
   CALL CHECK_INPUT
   CALL DELAY_1MS

SHOW_1:
   MOV DX, PORT_B
   MOV AL, 00000110B
   OUT DX, AL
   MOV DX, PORT_A
   MOV AL, 1
   OUT DX, AL
   CALL CHECK_INPUT
   CALL DELAY_1MS

SHOW_2:
   MOV DX, PORT_B
   MOV AL, 01011011B
   OUT DX, AL
   MOV DX, PORT_A
   MOV AL, 2
   OUT DX, AL
   CALL CHECK_INPUT
   CALL DELAY_1MS

SHOW_3:
   MOV DX, PORT_B
   MOV AL, 01001111B
   OUT DX, AL
   MOV DX, PORT_A
   MOV AL, 3
   OUT DX, AL
   CALL CHECK_INPUT
   CALL DELAY_1MS

SHOW_4:
   MOV DX, PORT_B
   MOV AL, 01100110B
   OUT DX, AL
   MOV DX, PORT_A
   MOV AL, 4
   OUT DX, AL
   CALL CHECK_INPUT
   CALL DELAY_1MS

SHOW_5:
   MOV DX, PORT_B
   MOV AL, 01101101B
   OUT DX, AL
   MOV DX, PORT_A
   MOV AL, 5
   OUT DX, AL
   CALL CHECK_INPUT
   CALL DELAY_1MS

SHOW_6:
   MOV DX, PORT_B
   MOV AL, 01111101B
   OUT DX, AL
   MOV DX, PORT_A
   MOV AL, 6
   OUT DX, AL
   CALL CHECK_INPUT
   CALL DELAY_1MS

SHOW_7:
   MOV DX, PORT_B
   MOV AL, 00000111B
   OUT DX, AL
   MOV DX, PORT_A
   MOV AL, 7
   OUT DX, AL
   CALL CHECK_INPUT
   CALL DELAY_1MS

SHOW_8:
   MOV DX, PORT_B
   MOV AL, 01111111B
   OUT DX, AL
   MOV DX, PORT_A
   MOV AL, 8
   OUT DX, AL
   CALL CHECK_INPUT
   CALL DELAY_1MS

SHOW_9:
   MOV DX, PORT_B
   MOV AL, 01101111B
   OUT DX, AL
   MOV DX, PORT_A
   MOV AL, 9
   OUT DX, AL
   CALL CHECK_INPUT
   CALL DELAY_1MS

   JMP EXEC_LOOP            

; Turn OFF display
CLEAR_DISP:
   MOV DX, PORT_B
   MOV AL, 00000000B
   OUT DX, AL
   MOV DX, PORT_A
   MOV AL, 0
   OUT DX, AL
   CALL DELAY_1MS
   JMP EXEC_LOOP

; Optimized input check
CHECK_INPUT:
   MOV DX, PORT_C
   IN AL, DX
   TEST AL, 00000001B   ; only check LSB
   JNZ CLEAR_DISP
   RET
   
; Delay Routine
DELAY_1MS:
   MOV BX, 02CAH
DELAY_LOOP:
   DEC BX
   NOP
   JNZ DELAY_LOOP
   RET

CODE_SEG ENDS
END MAIN_START
